#!/bin/bash
echo "=== SOST Alpha Stack Health ==="
echo ""
echo "--- Watcher Service ---"
systemctl is-active sost-alpha-watcher 2>/dev/null || echo "NOT RUNNING"
echo ""
echo "--- Dashboard API ---"
systemctl is-active sost-alpha-dashboard 2>/dev/null || echo "NOT RUNNING"
echo ""
echo "--- Dashboard Health Endpoint ---"
curl -s http://127.0.0.1:8080/health 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "Dashboard unreachable"
echo ""
echo "--- Sepolia Escrow Status ---"
curl -s http://127.0.0.1:8080/sepolia 2>/dev/null | python3 -m json.tool 2>/dev/null || echo "Sepolia endpoint unreachable"
